
export enum ModalityEnum {
  SOCCER = "SOCCER",
  BASKETBALL = "BASKETBALL",
  TENNIS = "TENNIS",
  VOLLEYBALL = "VOLLEYBALL",
  HANDBALL = "HANDBALL",
  GOLF = "GOLF",
  BASEBALL = "BASEBALL",
  HOCKEY = "HOCKEY",
  AMERICAN_FOOTBALL = "AMERICAN_FOOTBALL",
  RUGBY = "RUGBY",
}